### ISSUE TITLE
Analyse fastq from first QC - Ion Torrent

### ISSUE THREAD

**Issue by Alema91** [BU-ISCIII/viralrecon#21]
Try viralrecon with ion torrent samples.

**Comment by Alema91** [comment]
Amplicon used:
- Ion AmpliSeq™ SARS‑CoV‑2 Research Panel  
- Vela Diagnostics: ViroKey SQ FLEX SARS-CoV-2 Primer Set
- ARTIC v4

**Comment by Alema91** [comment]
Dificult to find the amplicon gff

**Comment by Alema91** [comment]
Try with the unique group that uses Artic v4 with Ion Torrent and we get this error:

```
Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:FASTQC_FASTP:FASTQC_RAW (COD_2105_10)'

Caused by:
  Process `NFCORE_VIRALRECON:ILLUMINA:FASTQC_FASTP:FASTQC_RAW (COD_2105_10)` terminated with an error exit status (1)

Command executed:

  [ ! -f  COD_2105_10.fastq.gz ] && ln -s COD_2105_10.fastq.gz COD_2105_10.fastq.gz
  fastqc --quiet --threads 6 COD_2105_10.fastq.gz
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_VIRALRECON:ILLUMINA:FASTQC_FASTP:FASTQC_RAW":
      fastqc: $( fastqc --version | sed -e "s/FastQC v//g" )
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /opt/ohpc/pub/libs/singularity/3.7.1/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Failed to process COD_2105_10.fastq.gz
  uk.ac.babraham.FastQC.Sequence.SequenceFormatException: ID line didn't start with '@'
  	at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:158)
  	at uk.ac.babraham.FastQC.Sequence.FastQFile.<init>(FastQFile.java:89)
  	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:106)
  	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
  	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:159)
  	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:121)
  	at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)

Work dir:
  /scratch/bi/20220228_VIRALRECON-QC/ANALYSIS/20220509_ANALYSIS01_AMPLICONS_HUMAN_iontorrent_v4/work/4f/ba74cbf418e49c60a07e4026d67ffd

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

**Comment by Alema91** [comment]
I have skipped FastQC in order to skip this error and works fine but with only two results:

```

-[nf-core/viralrecon] 2/8 samples passed Bowtie2 1000 mapped read threshold:
    162299: COD_2105_1
    64437: COD_2105_2
-
-[nf-core/viralrecon] 6 samples skipped since they failed Bowtie2 1000 mapped read threshold:
    0: COD_2105_10
    0: COD_2105_4
    0: COD_2105_3
    0: COD_2105_6
    0: COD_2105_9
    0: COD_2105_5
-
-[nf-core/viralrecon] Pipeline completed successfully-
Completed at: 09-May-2022 15:55:46
Duration    : 5m 25s
CPU hours   : 0.5
Succeeded   : 95

```

**Comment by Alema91** [comment]
The problem seems to be that the fastq than the labs are uploaded are corrupted.

**Comment by Alema91** [comment]
No answer from labs of coordenates of amplicons from Ampliseq and Virokey

**Comment by Alema91** [comment]
Problems with R&D department and confidential data

**Comment by Alema91** [comment]
We have the VELA amplicons coordenates!
